name: Dependency review

on:
  pull_request:
    branches: [feature/**]

permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-review:
    name: Review dependencies
    runs-on: ubuntu-latest
    # Allow this job to fail without blocking the workflow
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Dependency review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5
        with:
          fail-on-severity: moderate
